from . import camera_service
from . import face_detection_service
from . import eye_detection_service
from . import face_angle_service
from . import quality_assessment_service
from . import embedding_service
from . import face_registration_service
from . import face_recognition_service
from . import attendance_service
from . import attendance_scanner_service
from . import anti_spoofing_service